//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjectApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntityProductEntities : DbContext
    {
        public DbEntityProductEntities()
            : base("name=DbEntityProductEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Category> Table_Category { get; set; }
        public virtual DbSet<Table_Customer> Table_Customer { get; set; }
        public virtual DbSet<Table_Product> Table_Product { get; set; }
        public virtual DbSet<Table_Sales> Table_Sales { get; set; }
        public virtual DbSet<Table_Admin> Table_Admin { get; set; }
    
        public virtual ObjectResult<string> BRING()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BRING");
        }
    }
}
