//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjectApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_Sales = new HashSet<Table_Sales>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductBrand { get; set; }
        public Nullable<int> ProductStock { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Table_Category Table_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sales> Table_Sales { get; set; }
    }
}
